# Generated by Django 4.2.5 on 2024-12-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_start_time_usersession_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='session',
        ),
    ]
